<a href="https://colab.research.google.com/github/dhelawatad/ML/blob/master/numpyday1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy

In [0]:
  import numpy as np

In [3]:

a=np.array([2,7,1,99,4])
type(a)

numpy.ndarray

In [0]:
b=np.array([12,17,11,199,14])

In [5]:
a

array([ 2,  7,  1, 99,  4])

In [6]:
b

array([ 12,  17,  11, 199,  14])

In [7]:
a[0
]

2

In [8]:
a+b                                                    

array([ 14,  24,  12, 298,  18])

In [9]:
a**2

array([   4,   49,    1, 9801,   16])

In [10]:
a

array([ 2,  7,  1, 99,  4])

In [11]:
import numpy as np

a=np.array([2,3,5,79])
b=np.array([12,13,15,179])

c=a+b
print(c)


m=a*b
print(m)

a5=a+5
print(a5)


[ 14  16  20 258]
[   24    39    75 14141]
[ 7  8 10 84]


In [14]:
x=np.array([[2,5,8],[3,6,1]])
x

array([[2, 5, 8],
       [3, 6, 1]])

In [15]:
x[0]

array([2, 5, 8])

In [16]:
x[0][1]

5

In [17]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [0]:
y=x+7

In [20]:
y

array([[ 9, 12, 15],
       [10, 13,  8]])

In [0]:
z=np.array([[2,7],[3,8],[2,9],[9,4]])

In [23]:
z
66666666

66666666

In [24]:
z

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [25]:
z.shape


(4, 2)

In [26]:
z[0:2]

array([[2, 7],
       [3, 8]])

In [27]:
z[0:2,0]

array([2, 3])

In [28]:
z[0:2,1:2]

array([[7],
       [8]])

In [29]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [31]:
x[0:,[0,2]]

array([[2, 8],
       [3, 1]])

In [33]:
z[[0,3][1]]

array([9, 4])

In [34]:
z

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [35]:
z[3,1]

4

In [39]:
z[[0,3],1]


array([7, 4])

In [40]:
z[[0,3],[0,1]]

array([2, 4])

In [0]:
x1=x.reshape(3,2)

In [45]:
x1

array([[2, 5],
       [8, 3],
       [6, 1]])